CREATE TABLE wines_promotions(
   uuid                  INTEGER  NOT NULL PRIMARY KEY
  ,points                INTEGER  NOT NULL
  ,title                 VARCHAR(66) NOT NULL
  ,description           VARCHAR(494) NOT NULL
  ,taster_name           VARCHAR(12)
  ,taster_twitter_handle VARCHAR(10)
  ,price                 INTEGER  NOT NULL
  ,designation           VARCHAR(18)
  ,variety               VARCHAR(21) NOT NULL
  ,region_1              VARCHAR(11) NOT NULL
  ,region_2              VARCHAR(16)
  ,province              VARCHAR(12) NOT NULL
  ,country               VARCHAR(6) NOT NULL
  ,winery                VARCHAR(25) NOT NULL
  ,image                 VARCHAR(13) NOT NULL
);
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (27540,89,'Caymus 1998 Cabernet Sauvignon (Napa Valley)','Creamy black cherry aromas layered with fresh brussel sprouts and spicy arugula flavors of red plums and toasted oak.',NULL,NULL,70,NULL,'Cabernet Sauvignon','Napa Valley','Napa','California','US','Caymus','wine-007.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (45214,98,'M. Chapoutier 1999 Le Méal Ermitage  (Hermitage)','Chapoutier''s selections of the best parcels of vines in Hermitage are set to become legendary. Sold under the ancient spelling of the appellation name (Ermitage), they represent the epitome of the power and concentration that lies behind the reputation of the appellation. This cuvée is the best of the collection, with its brooding, opaque character, suggesting rather than revealing power at this stage. Age it until your new-born baby is old enough to drink, and it will be just about ready.','Roger Voss','@vossroger',150,'Le Méal Ermitage','Rhône-style Red Blend','Hermitage',NULL,'Rhône Valley','France','M. Chapoutier','wine-001.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (89469,97,'J.L. Chave 1999  Hermitage','Jean-Louis, the son of Gérard Chave, is now in charge of the family business, as well as being president of the Hermitage wine producers. He is continuing the family tradition of making powerful statements of Syrah from Hermitage, combining massive structure and over-powering perfumes. This 1999 seems to have the best of the traditional world of tannic immensity and the modern world of beautiful, ripe fruit. A wine that will age for a very long time.','Roger Voss','@vossroger',125,NULL,'Rhône-style Red Blend','Hermitage',NULL,'Rhône Valley','France','J.L. Chave','wine-011.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (24828,96,'Colgin 1999 Herb Lamb Vineyard Cabernet Sauvignon (Napa Valley)','Aromas lean toward black cherry, chocolate and herbs, which sally forth on the palate serving up more dense fruit, licorice, coffee and beautiful toast flavors. Tannins are smooth, supple and ripe. Long, lush and decadent on the finish.',NULL,NULL,150,'Herb Lamb Vineyard','Cabernet Sauvignon','Napa Valley','Napa','California','US','Colgin','wine-021.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (38466,96,'Stag''s Leap Wine Cellars 1998 SLV Cabernet Sauvignon (Napa Valley)','Certainly one of the successes of the vintage. Packed with cassis, sage, plum, tobacco, earth and smoky oak, and perfectly dry and balanced. Sheer joy in the mouth, like liquid velvet. It changes every second, offering up tiers of flavors through the spicy finish.',NULL,NULL,100,'SLV','Cabernet Sauvignon','Napa Valley','Napa','California','US','Stag''s Leap Wine Cellars','wine-010.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (51955,96,'Dalla Valle 1999 Maya Red (Napa Valley)','Plush, smooth and packed tight with complex flavors. Blackberry, anise, black cherry, tar, coal, spice, earth and herbs remain tightly wound, waiting patiently to reveal their full charm in time. Supple, smooth tannins and beautiful balance give this wine classic elegance.',NULL,NULL,120,'Maya','Red Blend','Napa Valley','Napa','California','US','Dalla Valle','wine-011.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (14745,96,'E. Guigal 1998 La Mouline  (Côte Rôtie)','Even though the 42 months this wine has spent in new wood give it an intensely toasty character, the enormously soft, perfumed fruits and ripe, sweet flavors that go along with the wood produce a finely tuned, balanced wine that should age well over many years. As an expression of pure Syrah, there are few better.','Roger Voss','@vossroger',175,'La Mouline','Rhône-style Red Blend','Côte Rôtie',NULL,'Rhône Valley','France','E. Guigal','wine-013.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (99396,95,'Quilceda Creek 1998 Cabernet Sauvignon (Washington)','After “fiddling around,” as he puts it, with blends in his ''96 and ''97 cabs, winemaker Alex Golitzin decided to go with straight Cabernet in ''98, an exceptional vintage for Washington State. This is a tight, focused effort, with powerful black fruits augmented with herbs and spices and a hint of mineral. Young, tart and tannic, it will continue to improve as it knits together over the years. Editors'' Choice.','Paul Gregutt','@paulgwine',60,NULL,'Cabernet Sauvignon','Washington','Washington Other','Washington','US','Quilceda Creek','wine-006.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (98591,95,'E. Guigal 1998 La Turque  (Côte Rôtie)','A firm, dry, foursquare wine that has power and structure rather than the immediate perfumes of La Mouline, the partner cuvée from Guigal. This is the wine for those who want power with big tannins, and they don''t come more powerful or tannic than this. Its aging potential is enormous:  after 10 years there should be more sign of the perfumed fruit which is there, somewhere.','Roger Voss','@vossroger',175,'La Turque','Rhône-style Red Blend','Côte Rôtie',NULL,'Rhône Valley','France','E. Guigal','wine-002.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (50370,95,'Domaine Jean-Michel Gerin 1999 La Landonne  (Côte Rôtie)','Here is a superbly rich and smooth wine. Aromas of violets and flavors of blueberries and red cherries along with dusty tannins, give this wine both immediate appeal and the promise of a good long-term future.','Roger Voss','@vossroger',150,'La Landonne','Rhône-style Red Blend','Côte Rôtie',NULL,'Rhône Valley','France','Domaine Jean-Michel Gerin','wine-003.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (60575,95,'Éric & Jöel Durand 1999 Empreintes  (Cornas)','A huge, ink-black wine with all the brooding majesty that gives Cornas its reputation. A blockbuster with enormous rich, sweet tannins. At the end it is the quality of the superripe fruit from old vines that dominates, but it is certainly a wine to keep for generations.','Roger Voss','@vossroger',37,'Empreintes','Rhône-style Red Blend','Cornas',NULL,'Rhône Valley','France','Éric & Jöel Durand','wine-004.webp');
INSERT INTO  wines_promotions(uuid,points,title,description,taster_name,taster_twitter_handle,price,designation,variety,region_1,region_2,province,country,winery,image) VALUES (85221,95,'E. Guigal 1999  Hermitage','A massive wine, with its opaque, dense purple color, its huge tannins and its tight, powerful structure. When it develops—maybe in 10 or 15 years'' time—the perfumed, juicy Syrah fruits that are just suggested for the moment are going to be as dominant as the tannins are now. What a wine it will be then.','Roger Voss','@vossroger',55,NULL,'Rhône-style Red Blend','Hermitage',NULL,'Rhône Valley','France','E. Guigal','wine-006.webp');
