/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import React, { useReducer } from "react";
import DropZone from "../components/DropZone";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from 'react';




export default function Home() {

  // const [name, setName] = useState()

  // useEffect(() => {

  //   (async () => {

  //     const response = await fetch(
  //'https://nextjs-integrator-v1.vercel.app/api/hello?q=wines_promotions'
  //'http://localhost:3000/api/users?order=id&sort=ASC&limit=1&offset=0&page=1'
  //    );
  //     const res = await response.json();
  //     console.log(res);
  //     setName(res)
  //   })()


  // }, [])




  // reducer function to handle state changes
  const reducer = (state, action) => {
    switch (action.type) {
      case "SET_IN_DROP_ZONE":
        return { ...state, inDropZone: action.inDropZone };
      case "ADD_FILE_TO_LIST":
        return { ...state, fileList: state.fileList.concat(action.files) };
      default:
        return state;
    }
  };

  // destructuring state and dispatch, initializing fileList to empty array
  const [data, dispatch] = useReducer(reducer, {
    inDropZone: false,
    fileList: [],
  });




  return (
    <div className={styles.container}>
      <Head>
        <title>Integrator-v1 Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs-integrator-v1.vercel.app/api/hello">Nextjs Integrator-v1</a>
        </h1>

        <p className={styles.description}>
          {`  eg.  ?q='wines_promotions' | 'users' | 'burger'`}
          <br />
          <code className={styles.code}>https://nextjs-integrator-v1.vercel.app/api/hello</code>
        </p>



        <div className={styles.grid}>


          <div className={styles.container}>

            <main className={styles.main}>
              <h1 className={styles.title}>Drag And Drop File Upload</h1>
              <br />
              {/* Pass state data and dispatch to the DropZone component */}
              <DropZone data={data} dispatch={dispatch} />
            </main>

          </div>

        </div>

        https://github.com/gisioraelvis/nextjs-dnd-fileupload-code/blob/master/pages/index.js
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
